import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import { getServerSession } from 'next-auth';
import Sidebar from '../shared/components/Sidebar';
import ClientRoot from '../shared/components/ClientRoot';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
    const session = await getServerSession();
    return (
        <html lang="ko">
            <body className={`bg-soopgray text-sooptext min-h-screen flex font-sans`}>
                <Sidebar />
                <div className="flex-1 md:ml-56 min-h-screen flex flex-col">
                    <ClientRoot session={session}>{children}</ClientRoot>
                </div>
            </body>
        </html>
    );
}
